name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check-js:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Vérification de la syntaxe JavaScript
        run: |
          node --check config.js
          node --check script.js